apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  name: PROJECTNAME
  namespace: PROJECT_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      release: PROJECTNAME
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        release: PROJECTNAME
      name: PROJECTNAME
    spec:
      containers:
      -
        image: PROJECTCONTAINERREGISTRY/PROJECTNAME:__COMMIT_ID__
        imagePullPolicy: Always
        name: PROJECTNAME
        resources:
          limits:
            cpu: 2000m
            memory: 4096Mi
          requests:
            cpu: 500m
            memory: 2096Mi
      imagePullSecrets:
      - name: secretnames
      restartPolicy: Always
